version: '3.5'

services:

  postgres:
    build:
      context: ./services/db
    environment:
      POSTGRES_DB: addressbook
      POSTGRES_USER: addressbook
      POSTGRES_PASSWORD: '123456'
    ports:
      - 5432:5432
    restart: always
    volumes:
        - ./tmp/postgres-data:/var/lib/postgresql/data
        - ./services/db/sql:/docker-entrypoint-initdb

  server:
    build:
      context: ./services/server
    ports:
      - 5001:5000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: addressbook
      POSTGRES_USER: addressbook
      POSTGRES_PASSWORD: '123456'
      POSTGRES_PORT: 5432
    depends_on:
      - postgres

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server